### ISSUE TITLE
DOM fragments localization for fluent-react

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#103]
As of `fluent-react` 0.4.1 it is possible to pass React elements as props to `<Localized>` to interpolate them into the translation:

```jsx
<Localized
    id="sign-in-or-cancel"
    $signInButton={
        <Localized id="sign-in-button">
            <button className="action" onClick={signIn}>{'Sign in'}</button>
        </Localized>
    }
    $cancelButton={
        <Localized id="cancel-button">
            <button className="text" onClick={cancel}>{'cancel'}</button>
        </Localized>
    }
>
    <p>{'{ $signInButton } or { $cancelButton}.'}</p>
</Localized>
```
```properties
sign-in-button = Sign in
cancel-button = cancel
sign-in-or-cancel = { $signInButton } or { $cancelButton }.
```

This is a bad localization practice because it results in the translation being split into multiple strings and then interpolated.

Instead we should do something similar to `fluent-dom`'s [overlay logic](https://github.com/projectfluent/fluent.js/blob/beabadab3e1fcb33a7ffbf736dd237fc63d2833f/fluent-dom/src/overlay.js).

#### Solution

With overlays, the translation can include some HTML which will be parsed by Fluent. HTML children found in the translation are then matched against child elements in the source. In React, we can pass the source elements via props.

```jsx
<Localized
    id="sign-in-or-cancel"
    button={
        <button className="action" onClick={signIn}></button>
    }
    a={
        <button className="text" onClick={cancel}></button>
    }
>
    <p>{'<button>Sign in</button> or <a>cancel</a>.'}</p>
</Localized>
```
```properties
sign-in-or-cancel = <button>Sign in</button> or <a>cancel</a>.
```

#### To Do

  - [x] Initial support without sanitation nor customization. (#101)
  - [x] Forbid setting translated content in void elements. (#105)
  - [x] Allow developers to create attribute filters for elements wrapped in `<Localized>`. (#139)
  - [ ] Create default filters for safe attributes on known HTML elements (e.g. allow `placeholder` on `input` but forbid the localization to set `href` on an `a` element).
  - [ ] Allow controlling which attributes are allowed on children found in translations.
  - [ ] Allow localizers to use text-level elements like `<em>` and `<sup>` even if the source doesn't have them.

**Comment by stasm** [comment]
This was fixed in #101 and then a few follow-ups landed in #105, #141, #154 and #155. I continued to use this issue to track overlay-related features. I'm now closing it for good and I'll be using the [overlay](https://github.com/projectfluent/fluent.js/labels/overlay) label for the same purpose.
