### ISSUE TITLE
fluent-syntax: Implement Syntax 0.6

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#206]
A tracking issue for implementing [Syntax 0.6](https://github.com/projectfluent/fluent/projects/2) in `fluent-syntax`.

- [x] Port fixtures from the reference parser. (#239)
- [x] Named arguments to `CallExpression` must now follow all positional ones. (#215)
- [x] Forbid duplicate named arguments to `CallExpressions`. (#215)
- [x] Add the `TermReference` expression. (#226)
- [x] Store the referent expression in `AttributeExpression`. (#224)
  - This is already true in `VariantExpression`.
- [x] Rename `ExternalArgument` to `VariableReference`. (#214)
- [x] Introduce the `VariantList` value type. (#232)
- [x] Rename `NumberExpression` to `NumberLiteral`. (#214)
- [x] Rename `StringExpression` to `StringLiteral`. (#214)
- [x] Remove the abstract `Expression` AST node. (2d5b48c81849406574465b800696bc1d49bceaf8)
- [x] Rename `SelectExpression.expression` to `selector`. (8fc69440fcc091821d45aca4e90b8ee51b604569)
- [x] Parse `Comments` as standalone when the `Message` they're attached to is `Junk`. (#235)

**Comment by zbraniecki** [comment]
I started working on that and hit two incompatibilities between fluent-syntax and reference parser that I'd like to flag:

 - TermReference's name is `-term`. It seems a bit redundant and inconsistent. VariableReference's name is `var, not `$var`.
 - When a comment is attached to a message it's part of its AST, but when there's an error in that message, its comment is added to AST separately and only the message is turned into junk. That seems inconsistent.

I'd like to get your opinion @stasm - is that an intentional change?

**Comment by Pike** [comment]
I think I can unblock us here before Tuesday, thus:

> TermReference's name is -term. It seems a bit redundant and inconsistent. VariableReference's name is var, not $var.

I think that's good that way. The IDs of a Term also include the '-' as they are represented in the source. Variables are actually a bit odd, in that their API-level name is without the `$`, but their l10n-level name is with it. If we wanted to make that consistent, I'd lean towards changing the `VariableReference` rather than `Term` and `TermReference`.

I don't think this changed the way referencing Terms works, the existing behavior just got a dedicated name.

> When a comment is attached to a message it's part of its AST, but when there's an error in that message, its comment is added to AST separately and only the message is turned into junk. That seems inconsistent.

I think this is part of error recovery. When we hit a parse error, we try to recover from errors where we started, and that resurrects the standalone comment, and just a Junk entry afterwards.

The change that introduced this is that we're formally declaring at which point a standalone comment becomes a comment bound to a Message or Term. In that sense I think it's OK to not bind comments to Junk. That's also how for example compare-locales would represent the 0.5 syntax.

There are interesting opportunities to make errors bigger in support for better messages and representation of the AST after the error was fixed. stas did think about folding errors that are likely inside an attribute of a message into the message itself. Not sure what's "likely" here, though. And how to implement that with the current reference parser setup while creating the right error message. Which means we can't just fix hack that in `abstract.mjs`, which we could for comments-bound-to-junk once we have top-level white-space (projectfluent/fluent/issues/116).

Within the scope of 0.6, I'd call both good to go.

**Comment by zbraniecki** [comment]
> I don't think this changed the way referencing Terms works, the existing behavior just got a dedicated name.

I'm not convinced that this is the right model. Looking at every AST I can find (JS, Python, Rust, PHP), the value never redundantly duplicates the data carries by the node type.

In our case, Variables don't carry the variable sigil, and Comments don't carry the `#` sigil either.

In the EBNF it clearly is represented as:

```
Comment            ::= ("#" comment_line)+
TermIdentifier      ::= "-" identifier
VariableIdentifier ::= "$" identifier
```

In JS, Python, PHP and Rust if a bit of information is encoded by the AST node type, it is not stored in any node field's content. Can you point me to any prior work example where it works differently or explain why, in your opinion, this case is different?

> I think this is part of error recovery. When we hit a parse error, we try to recover from errors where we started, and that resurrects the standalone comment, and just a Junk entry afterwards.

This seems like breakage of the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) - the new behavior changes the semantic role of a bit of information encoded in FTL file depending whether there was an error or not. This means that if someone writes a comment meant to be attached to a message, and there's an error in the message, they may end up with a standalone comment.
Now, this is not very consequential right now, but there's nothing guaranteeing that we won't have some behaviors expected for standalone vs. message comments.
Of course once an error happens, we just try to salvage, but in this case we *do* know that the comment was meant to be attached to the message, and yet we *choose* to encode it as a standalone.

Can you point out any prior example of such behavior in any programming system? I tried to imagine such behavior in CSS, for example, and cannot find a case where a node is encoded differently than was intended despite the parser being able to identify the intention of the author.

After thinking about it a bit more, I'd like to suggest changing those two behaviors.

**Comment by Pike** [comment]
Neither discussion belongs into this ticket.

To reiterate the scope of 0.6, it's about being as close to 0.5 as possible, but sane. If there's stuff that needs to change, it's most likely a later milestone, maybe things to be backed out for 0.6 (and possibly for good).

**Comment by stasm** [comment]
@zbraniecki Would you mind opening two issues in https://github.com/projectfluent/fluent to continue these discussions? Let's triage them at the next meeting.

**Comment by zbraniecki** [comment]
@stasm - took VariantList, but unchecked the test coverage. I can't plug reference fixtures into fluent syntax due to incompatibilities in treating Junk Message.

If we don't resolve it in 0.6, then I don't think we can plug reference fixtures in fluent-syntax 0.6.

**Comment by stasm** [comment]
OK, thanks. Do you mean the incompatibility in parsing `Comments` as standalone when the `Message` they're attached to is `Junk`? Let's tackle this as a separate item. I added it end of the list. I remember we discussed a few approaches: an extra `try…catch` in `getEntry` or rewinding the index. Let me know if you'd like to experiment with them. If not, I'll do it next week.
