### ISSUE TITLE
Implement Syntax 0.8

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#303]
Let's plan the implementation work in this issue. We'll submit PRs against a release branch, `zeroeight`, which I'll create later today.

Some 0.8 features don't need any work in `fluent.js`: https://github.com/projectfluent/fluent/pull/179 and https://github.com/projectfluent/fluent/pull/207 are already supported and https://github.com/projectfluent/fluent/pull/211 made the reference parser behave like the tooling one.

For features that need implementation, I'd like to follow the same order in which they landed in the spec. This will make it much easier to keep the reference tests green with each change. Here's the full list:

#### Part 1 (#307)

- [x] 1. Support astral Unicode characters in TextElements and StringLiterals
    https://github.com/projectfluent/fluent/pull/179, tests only
- [x] 2. Don't store the term sigil in the identifier name
    https://github.com/projectfluent/fluent/pull/183, tooling parser
- [x] 3. Treat backslash as normal char in TextElements
    https://github.com/projectfluent/fluent/pull/181, tooling parser, runtime parser
- [x] 4. Don't normalize CRLF to LF in Junk
    https://github.com/projectfluent/fluent/pull/193, tests only
- [x] 5. Forbid the closing brace in text
    https://github.com/projectfluent/fluent/pull/198, tooling parser, runtime parser

#### Part 2 (#309)

- [x] 6. Dedent multiline text to preserve content indentation
    https://github.com/projectfluent/fluent/pull/197, tooling parser, runtime parser

#### Part 3 (#310)

- [x] 7. Add FunctionReference
    https://github.com/projectfluent/fluent/pull/210, tooling parser
- [x] 8. Store unescaped content in StringLiteral.value and raw content in StringLiteral.raw
    https://github.com/projectfluent/fluent/pull/203, tooling parser

#### Part 4 (#311)

- [x] 9. Add Parameterized Terms
    https://github.com/projectfluent/fluent/pull/205, tooling parser, runtime parser, resolver

#### Part 5 (#312)

- [x] 10. Stop parsing Junk on lines which look like Entries
    https://github.com/projectfluent/fluent/pull/211, tests only
- [x] 11. Allow all Unicode characters
    https://github.com/projectfluent/fluent/pull/207, tests only

#### Part 6 (#313)

- [x] 12. Add Parameterized Attributes
    https://github.com/projectfluent/fluent/pull/212, tooling parser, runtime parser, resolver

#### Part 7 (#314)

- [x] 13.  Recognize \UHHHHHH as an escape sequence
    https://github.com/projectfluent/fluent/pull/201, tooling parser, runtime parser
- [x] 14. Change line endings in comments to line_end
    https://github.com/projectfluent/fluent/pull/219, tooling parser
- [x] 15. Forbid nested VariantLists
    https://github.com/projectfluent/fluent/pull/220, tooling parser
